;;; web-beautify-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from web-beautify.el

(autoload 'web-beautify-html "web-beautify" "\
Format region if active, otherwise the current buffer.

Formatting is done according to the html-beautify command." t)
(autoload 'web-beautify-html-buffer "web-beautify" "\
Format the current buffer according to the html-beautify command.")
(autoload 'web-beautify-css "web-beautify" "\
Format region if active, otherwise the current buffer.

Formatting is done according to the css-beautify command." t)
(autoload 'web-beautify-css-buffer "web-beautify" "\
Format the current buffer according to the css-beautify command.")
(autoload 'web-beautify-js "web-beautify" "\
Format region if active, otherwise the current buffer.

Formatting is done according to the js-beautify command." t)
(autoload 'web-beautify-js-buffer "web-beautify" "\
Format the current buffer according to the js-beautify command.")
(register-definition-prefixes "web-beautify" '("web-beautify-"))

;;; End of scraped data

(provide 'web-beautify-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; web-beautify-autoloads.el ends here
