;;; helm-ag-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-ag.el

(autoload 'helm-ag-pop-stack "helm-ag" "\
Restore the previous search context from the `helm-ag--context-stack'." t)
(autoload 'helm-ag-clear-stack "helm-ag" "\
Clear all entries in the `helm-ag--context-stack'." t)
(autoload 'helm-ag-this-file "helm-ag" "\
Do ag with in this file with QUERY.

(fn &optional QUERY)" t)
(autoload 'helm-ag "helm-ag" "\
Do ag with in BASEDIR and with QUERY.

(fn &optional BASEDIR QUERY)" t)
(autoload 'helm-do-ag-this-file "helm-ag" "\
Execute `helm-do-ag' Search in the current file.

(fn &optional QUERY)" t)
(autoload 'helm-do-ag "helm-ag" "\
Execute a `helm-do-ag' search in the specified directory or files.

BASEDIR: An optional directory in which to perform the search. If not
specified, the current directory is used.
TARGETS: A list of files or directories to search. If not provided,
  the user will be prompted to select files.
DEFAULT-INPUT: An optional string that serves as the initial input for
  the search.

The function initializes the helm state, determines the default directory
and target, and sets up the helm source for searching. It handles Windows
specific behavior for path arguments and saves the current context for
subsequent searches.

(fn &optional BASEDIR TARGETS DEFAULT-INPUT)" t)
(autoload 'helm-ag-project-root "helm-ag" "\
Execute `helm-ag' in the project directory with optional default input QUERY.

(fn &optional QUERY)" t)
(autoload 'helm-do-ag-project-root "helm-ag" "\
Execute `helm-do-ag' in the project directory with optional default input QUERY..

(fn &optional QUERY)" t)
(autoload 'helm-ag-buffers "helm-ag" "\
Execute `helm-ag' in all buffers with optional default input QUERY.

(fn &optional QUERY)" t)
(autoload 'helm-do-ag-buffers "helm-ag" "\
Execute `helm-do-ag' in all buffers with optional default input QUERY.

(fn &optional QUERY)" t)
(register-definition-prefixes "helm-ag" '("helm-"))

;;; End of scraped data

(provide 'helm-ag-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-ag-autoloads.el ends here
