;;; org-randomnote-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-randomnote.el

(autoload 'org-randomnote "org-randomnote" "\
Go to a random note satisfying Org match within a random Org file.

(fn &optional MATCH)" t)
(register-definition-prefixes "org-randomnote" '("org-randomnote-"))

;;; End of scraped data

(provide 'org-randomnote-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-randomnote-autoloads.el ends here
