;;; smart-mode-line-powerline-theme-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from smart-mode-line-light-powerline-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "smart-mode-line-light-powerline-theme" '("smart-mode-line-light-powerline"))


;;; Generated autoloads from smart-mode-line-powerline-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "smart-mode-line-powerline-theme" '("smart-mode-line-powerline"))

;;; End of scraped data

(provide 'smart-mode-line-powerline-theme-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; smart-mode-line-powerline-theme-autoloads.el ends here
