(source gnu)
(source melpa)

(depends-on "dash")
(depends-on "s")
(depends-on "f")
(depends-on "web")

; starter-kit dependencies
(depends-on "paredit")
(depends-on "idle-highlight-mode")

; needed explicitly for some reason
(depends-on "elisp-slime-nav")

(depends-on "magit")
(depends-on "monky")
(depends-on "yasnippet")
(depends-on "move-text")
(depends-on "htmlize")
(depends-on "free-keys")
(depends-on "ace-jump-mode")
(depends-on "ace-window")
(depends-on "company")
(depends-on "projectile")
(depends-on "helm")
(depends-on "helm-projectile")
(depends-on "helm-swoop")
(depends-on "helm-descbinds")

(depends-on "haskell-mode")
(depends-on "ghc")
(depends-on "coffee-mode")
(depends-on "groovy-mode")
(depends-on "scala-mode2")
(depends-on "sbt-mode")
(depends-on "ensime")
(depends-on "clojure-mode")
(depends-on "cider")
(depends-on "js2-mode")
(depends-on "markdown-mode")

(depends-on "4clojure")
