;;; toggle-quotes-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from toggle-quotes.el

(autoload 'toggle-quotes "toggle-quotes" "\
Toggle between single quotes and double quotes." t)
(register-definition-prefixes "toggle-quotes" '("tq/"))

;;; End of scraped data

(provide 'toggle-quotes-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; toggle-quotes-autoloads.el ends here
