;;; xref-js2-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from xref-js2.el

(autoload 'xref-js2-xref-backend "xref-js2" "\
Xref-Js2 backend for Xref.")
(register-definition-prefixes "xref-js2" '("xref-js2-"))

;;; End of scraped data

(provide 'xref-js2-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; xref-js2-autoloads.el ends here
