;;; pacfiles-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from pacfiles-automerge.el

(autoload 'pacfiles--automerge-available "pacfiles-automerge" "\
Return the function that knows how to merge UPDATE-FILE if it exists.

UPDATE-FILE searches for matches in `pacfiles--automerge-alist'. If a match is
found, return a function, otherwise return nil.

(fn UPDATE-FILE)")
(autoload 'pacfiles--automerge-mirrorlist "pacfiles-automerge" "\
Automatically merge the mirrorlist in BASE-FILE into UPDATE-FILE.

(fn BASE-FILE UPDATE-FILE)")
(autoload 'pacfiles--find-mirrorlist-servers "pacfiles-automerge" "\
Find the activated servers (i.e., those uncommented) in BASE-BUFFER.

(fn BASE-BUFFER)")
(autoload 'pacfiles--create-mirrorlist-merge-buffer "pacfiles-automerge" "\
Ready up the merge buffer for the mirrorlist.

The MIRRORLIST-UPDATE-FILE is the path of the original mirrorlist. UPDATE-BUFFER
is the buffer with the updated mirrorlist. Return the buffer of the merged file.

(fn MIRRORLIST-UPDATE-FILE UPDATE-BUFFER)")
(autoload 'pacfiles--merge-mirrorlist-servers "pacfiles-automerge" "\
Automatically merge the mirrorlist update in MIRRORLIST-UPDATE-FILE.

Merge the uncommented lines in SERVERS that exist in UPDATE-BUFFER.

(fn SERVERS MIRRORLIST-UPDATE-FILE UPDATE-BUFFER)")
(register-definition-prefixes "pacfiles-automerge" '("pacfiles--automerge-alist"))


;;; Generated autoloads from pacfiles-buttons.el

(register-definition-prefixes "pacfiles-buttons" '("pacfiles-"))


;;; Generated autoloads from pacfiles-mode.el

(defalias 'pacfiles 'pacfiles-start)
(autoload 'pacfiles-start "pacfiles-mode" "\
Find and manage pacman backup files in an Arch-based GNU/Linux system." t)
(autoload 'pacfiles-quit "pacfiles-mode" "\
Quit ‘pacfiles-mode’ and restore the previous window and ediff configuration." t)
(autoload 'pacfiles-revert-buffer "pacfiles-mode" "\
Populate the ‘pacfiles-mode’ buffer with .pacnew and .pacsave files.

Ignore IGNORE-AUTO but take into account NOCONFIRM.

(fn &optional IGNORE-AUTO NOCONFIRM)" t)
(autoload 'pacfiles-revert-buffer-no-confirm "pacfiles-mode" "\
Revert the pacfiles list buffer without asking for confirmation." t)
(autoload 'pacfiles-mode "pacfiles-mode" "\


(fn)" t)
(register-definition-prefixes "pacfiles-mode" '("pacfiles-"))


;;; Generated autoloads from pacfiles-utils.el

(register-definition-prefixes "pacfiles-utils" '("pacfiles--"))


;;; Generated autoloads from pacfiles-win.el

(register-definition-prefixes "pacfiles-win" '("pacfiles-"))

;;; End of scraped data

(provide 'pacfiles-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; pacfiles-mode-autoloads.el ends here
